# Generated by Django 4.2.3 on 2023-07-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_scheduledemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledEmail',
        ),
    ]
