# Generated by Django 4.2.3 on 2023-07-19 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_email_attachments_dir_email_is_sent_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='attachment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AttachmentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
